[directory]
truncate_to_repo = false

[time]
disabled = false
format = '🕙[ $time ]($style)'

[package]
disabled = true

[custom.sudo]
description = "valid sudo timestamp marker"
command = "echo -n '!'"
format = "[$symbol$output]($style) "
style = "bold fg:bright-red"
when = "sudo -vn &>/dev/null"

